input {
  file {
    path => "/usr/share/logstash/nginx_logs.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  csv {
    separator => ","
    columns => ["ip_address", "dash1", "dash2", "timestamp", "method", "endpoint", "protocol", "status_code", "bytes", "referrer", "user_agent"]
  }

  mutate {
    remove_field => ["dash1", "dash2"]
  }

  date {
    match => ["timestamp", "dd/MMM/yyyy:HH:mm:ss Z", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx_logs"
  }

  stdout { codec => rubydebug }
}